// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: deletes.sql

package db

import (
	"context"
	"database/sql"
)

const removeAccount = `-- name: RemoveAccount :exec
DELETE FROM users_info.accounts
WHERE aid = $1
`

func (q *Queries) RemoveAccount(ctx context.Context, aid int64) error {
	_, err := q.db.Exec(ctx, removeAccount, aid)
	return err
}

const removeProfile = `-- name: RemoveProfile :exec
DELETE FROM users_info.profiles
WHERE aid = $1
`

func (q *Queries) RemoveProfile(ctx context.Context, aid sql.NullInt64) error {
	_, err := q.db.Exec(ctx, removeProfile, aid)
	return err
}
