/*
Copyright 2023 Francisco Simões Braço-Forte

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: deletes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const removeAccount = `-- name: RemoveAccount :exec
DELETE FROM users_info.accounts
WHERE aid = $1
`

func (q *Queries) RemoveAccount(ctx context.Context, aid uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAccount, aid)
	return err
}

const removeProfile = `-- name: RemoveProfile :exec
DELETE FROM users_info.profiles
WHERE aid = $1
`

func (q *Queries) RemoveProfile(ctx context.Context, aid uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, removeProfile, aid)
	return err
}
