/*
Copyright 2023 Francisco Simões Braço-Forte

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/twpayne/go-geom"
)

type UsersInfoAccount struct {
	Aid         uuid.UUID
	Username    string
	Email       string
	Password    string
	PhonePrefix sql.NullInt32
	PhoneNumber sql.NullInt32
}

type UsersInfoProfile struct {
	Pid         uuid.UUID
	Aid         uuid.NullUUID
	Description sql.NullString
	FirstName   string
	MiddleName  sql.NullString
	Surname     string
	Location    geom.MultiPolygon
}
